### ISSUE TITLE
Connectivity to SR and Forums is timing out

### ISSUE THREAD

**Issue by GalacticMuseum** [Primeaxiom/StellarRealms#45] opened 2016-02-14 13:10 UTC
I am unable to get to the SR webpage or the forums webpage. Connectivity times out. I can get to other websites. Problem exists in both Firefox and IE.

When I ping www.stellar-realms.com I receive a TTL expire in transit error.

**Comment by jbyron** [comment] 2016-03-11 03:28
I'm closing this as I have seen no other reports of this and was not able to reproduce this at all.  If it re-occurs let me know and we will reopen the issue.

**Closed as completed by jbyron** 2016-03-11 03:28 UTC
